baseURL = "https://zvenyach.com/"
languageCode = "en-us"
title = "Zvenyach LLC website"


[params]
  description = "Zvenyach LLC: Helping businesses and government work smarter, together."
  images = ["/images/Zvenyach-Logo.png"]
  title = "Zvenyach LLC's website"

[taxonomies]
  series = "series"
